#!/usr/bin/env python

from PIL import Image
import glob, os
import re


ratio = 4/3.

print "ratio = {}".format(ratio)

matchedFiles = [f for f in os.listdir('.') if re.search(r'.*\.[jpg|JPG]', f)]

for infile in matchedFiles:
	print "reading {}".format(infile)
	file, ext = os.path.splitext(infile)
	image = Image.open(infile)
	imgWidth = image.size[0]
	imgHeight = image.size[1]

	width 	= 0
	height 	= 0



	if imgWidth*(1/ratio) >= imgHeight:
		width 	= imgHeight*ratio
		height 	= imgHeight
		top = 0
		left = (imgWidth - width) / 2
	else:
		width 	= imgWidth
		height 	= imgWidth*(1/ratio)
		left = 0
		top = (imgHeight - height) / 2
	print "({}x{})".format(width, height), (imgWidth, imgHeight), (left, top, left+width, top+height), file
	
	#image.crop( (int(left), int(top), int(left+width), int(top+height)) ).save("thumb"+file + ".jpg", "JPEG")
	
	