#!/usr/bin/env python

from PIL import Image
import glob, os
import re


ratio = 4/3.
thumb_path = "mini"

print "ratio = {}".format(ratio)

matchedFiles = [f for f in os.listdir('.') if re.search(r'.*\.[jpg|JPG]', f)]

# Create folder 'mini'
if not os.path.exists(thumb_path):
	os.mkdir(thumb_path)

for infile in matchedFiles:
	print "reading {}".format(infile)

	image = Image.open(infile)
	imgWidth = image.size[0]
	imgHeight = image.size[1]
	
	# Calculate new resolution
	width 	= 0
	height 	= 0

	if imgWidth*(1/ratio) >= imgHeight:
		width 	= imgHeight*ratio
		height 	= imgHeight
		top = 0
		left = (imgWidth - width) / 2
	else:
		width 	= imgWidth
		height 	= imgWidth*(1/ratio)
		left = 0
		top = (imgHeight - height) / 2

	# Crop and save	
	filename, ext = os.path.splitext(infile)
	print "({}x{})".format(width, height), (imgWidth, imgHeight), (left, top, left+width, top+height), filename
	
	outfile = os.path.join(os.getcwd(), thumb_path, filename+ext)
	print "Cropping and saving to {}".format(outfile)

	image.crop( (int(left), int(top), int(left+width), int(top+height)) ).save(outfile, "JPEG")

print "done..."

